name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run-script build-prod
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # ftp server
        server: ${{ secrets.FTP_HOST }}
        # ftp username
        username: ${{ secrets.FTP_USERNAME }}
        # ftp password
        password: ${{ secrets.FTP_PASSWORD }}
        # Server port to connect to (read your web hosts docs)
        port: 21
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftp
        # Folder to upload from, must end with trailing slash /
        local-dir: ./www/
  
